# =============================================================================
# EXTERNAL SECRETS OPERATOR
# =============================================================================
# Docs: https://external-secrets.io/latest/introduction/getting-started/
#
# Syncs secrets from external providers (Doppler, AWS, Vault, etc.) to K8s.
# No changes needed - uses official Helm chart.
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    # Wave 4: secrets operator
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Official Helm chart - no changes needed
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    # OPTIONAL: Update version as needed (check https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets)
    targetRevision: "0.15.1"
    helm:
      values: |
        installCRDs: true
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
