# Longhorn - Distributed block storage for Kubernetes
# Docs: https://longhorn.io/docs/1.10.1/deploy/install/install-with-argocd/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: "1.10.1"
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
