# =============================================================================
# CLUSTER SECRET STORES - ALL ENVIRONMENTS
# =============================================================================
# Docs: https://external-secrets.io/latest/provider/doppler/
#
# Deploys all ClusterSecretStore manifests from manifests/cluster-secret-stores/
# Add new environment by creating new file: doppler-<env>.yaml
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-stores
  namespace: argocd
  annotations:
    # Wave 5: after ESO
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Uses values from apps/values.yaml (no changes needed here)
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    # Keep as-is: path to ClusterSecretStore manifests
    path: manifests/infra/cluster-secret-stores
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
