apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: git@github.com:mshykhov/example-deploy.git
        revision: HEAD
        files:
          - path: "services/**/config.json"
  template:
    metadata:
      name: '{{`{{ .name }}`}}'
    spec:
      project: '{{`{{ .project }}`}}'
      source:
        repoURL: git@github.com:mshykhov/example-deploy.git
        targetRevision: HEAD
        path: '{{`{{ .chartPath }}`}}'
      destination:
        server: {{ .Values.spec.destination.server }}
        namespace: '{{`{{ .namespace }}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
