apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: git@github.com:mshykhov/example-deploy.git
        revision: HEAD
        directories:
          - path: services/*
          - path: services/_*
            exclude: true
  template:
    metadata:
      name: '{{`{{ .path.basename }}`}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:mshykhov/example-deploy.git
        targetRevision: HEAD
        path: '{{`{{ .path.path }}`}}'
      destination:
        server: {{ .Values.spec.destination.server }}
        namespace: '{{`{{ .path.basename }}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
