# =============================================================================
# UPTIME KUMA - Status Page & Monitoring
# =============================================================================
# Docs: https://github.com/louislam/uptime-kuma
# Chart: https://github.com/dirsigler/uptime-kuma-helm
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "35"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://dirsigler.github.io/uptime-kuma-helm
      chart: uptime-kuma
      targetRevision: "2.24.0"
      helm:
        valueFiles:
          - $values/helm-values/monitoring/uptime-kuma.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: values
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
