# =============================================================================
# AUTH0 CREDENTIALS - ExternalSecret for oauth2-proxy
# =============================================================================
# Creates namespace and ExternalSecret for Auth0/oauth2-proxy secrets.
# Must sync BEFORE oauth2-proxy (wave 14 < wave 15).
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth0-credentials
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "14"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: manifests/network/auth0-credentials
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: oauth2-proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
