# =============================================================================
# CERT-MANAGER
# =============================================================================
# Docs: https://cert-manager.io/
#
# Provides:
# - Automatic TLS certificate management
# - Let's Encrypt integration
# - Certificate renewal
#
# Usage:
# - ClusterIssuer created separately (manifests/network/cert-manager-issuer/)
# - Used for public services (example-api via MetalLB)
# - Internal services use Tailscale TLS instead
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: "v1.17.2"
      helm:
        valueFiles:
          - $values/helm-values/network/cert-manager.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: values
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
