# =============================================================================
# CERT-MANAGER CLUSTER ISSUERS
# =============================================================================
# Creates ClusterIssuers for Let's Encrypt:
# - letsencrypt-prod: Production certificates
# - letsencrypt-staging: Testing (no rate limits)
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "14"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: manifests/network/cert-manager-issuer
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
