# =============================================================================
# NGINX CUSTOM HEADERS
# =============================================================================
# ConfigMap for custom proxy headers
# Must deploy BEFORE nginx-ingress (wave 11)
# Docs: https://kubernetes.github.io/ingress-nginx/examples/customization/custom-headers/
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-custom-headers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: manifests/network/nginx-custom-headers
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
