# =============================================================================
# OAUTH2-PROXY
# =============================================================================
# Docs: https://oauth2-proxy.github.io/oauth2-proxy/
# Chart: https://github.com/oauth2-proxy/manifests
#
# Provides authentication middleware for NGINX Ingress.
# Uses Auth0 as OIDC provider.
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://oauth2-proxy.github.io/manifests
      chart: oauth2-proxy
      targetRevision: "7.18.0"
      helm:
        valueFiles:
          - $values/helm-values/network/oauth2-proxy.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: values
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: oauth2-proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
