# =============================================================================
# PROTECTED SERVICES
# =============================================================================
# Tailscale LoadBalancers + NGINX Ingresses + oauth2-proxy for internal services
# Configure in: charts/protected-services/values.yaml
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: protected-services
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "17"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: charts/protected-services
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
