# =============================================================================
# TAILSCALE SERVICE FOR NGINX INGRESS
# =============================================================================
# Exposes NGINX Ingress Controller to tailnet as internal.tailnet-xxxx.ts.net
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-nginx-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: manifests/network/tailscale-nginx-service
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
