# =============================================================================
# TAILSCALE CREDENTIALS - ExternalSecret for OAuth
# =============================================================================
# Docs: https://tailscale.com/kb/1236/kubernetes-operator
#
# Creates namespace and ExternalSecret for Tailscale OAuth credentials.
# Must sync BEFORE tailscale-operator (wave 9 < wave 10).
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-credentials
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: manifests/network/tailscale-credentials
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
