# =============================================================================
# NODE TUNING - Kernel parameters for observability stack
# =============================================================================
# Fixes inotify limits for Alloy log collection
# Must run before monitoring stack (wave 29)
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-tuning
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "29"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: manifests/core/node-tuning
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
